version: '3.8'

services:
  webapi:
    image: mi-webapi:latest
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
#      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
      - "8181:8181"
    network_mode: "host"
#    networks:
#      - mynetwork
#     network_mode: "host"
#networks:
#  mynetwork:
#    driver: bridge
