# This is a generated file. Not intended for manual editing.
services:
  webapi:
    build:
      context: "/home/wdg/RiderProjects/SystemCongress"
      dockerfile: "Web.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Web.Api.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "mi-webapi:dev"
    ports: []
    volumes:
    - "/home/wdg/RiderProjects/SystemCongress/Web.Api:/app:rw"
    - "/home/wdg/RiderProjects/SystemCongress:/src:rw"
    - "/home/wdg/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
